<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="google-site-verification" content="MUDP2J4JyyfKSWJsjfuglidOXiHOU_vn5VLXY7S-G8w" />
        <title>hukumonline.com Identity</title>
        <link href="<?=$this->cdn('styles')?>/favicon.ico" rel="shortcut icon" type="image/ico" />
        <link href="<?=$this->cdn('styles')?>/typography.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="<?=$this->cdn('styles')?>/identity.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="<?=$this->cdn('styles')?>/store.css" media="screen" rel="stylesheet" type="text/css" />
        <script type="text/javascript" src="<?=$this->cdn('scripts')?>/index.php?c=auto&amp;f=,hol/jquery/jquery-1.4.2.min.js,hol/jquery/form/jquery.validate.pack.js" ></script>

        <!-- Internet Explorer Fixes -->
        <!--[if IE]>

        <link rel="stylesheet" type="text/css" media="all" href="<?=$this->cdn('styles')?>/ie.css"/>

        <script src="<?=$this->cdn('scripts')?>/hol/html5.js"></script>

        <![endif]-->
        <!--Upgrade MSIE5.5-7 to be compatible with MSIE8: http://ie7-js.googlecode.com/svn/version/2.1(beta3)/IE8.js -->
        <!--[if lt IE 8]>

        <script src="<?=$this->cdn('scripts')?>/hol/IE8.js"></script>

        <![endif]-->

    </head>
    <body>
        <div id="page">
            <div class="wrapper">
                <div id="judul"><a href="<?=ROOT_URL;?>"><img src="<?=$this->cdn('images');?>/holid.jpg" alt="hukumonline" /></a></div>
                <div class="align-left">
                <small>.:Hukumonline-ID</small>
                </div>
                <div class="align-right">
                    <a href="<?=ROOT_URL;?>">hukumonline.com</a> | <a href="http://en.hukumonline.com">en.hukumonline.com</a> | <a href="http://hukumpedia.com">hukumpedia.com</a> | <a href="http://forum.hukumonline.com">forum.hukumonline.com</a>
                </div>
                <div class="clear">&nbsp;</div>
                <hr>
                <section class="column first">
                    <div class="colgroup leading">
                        <div class="column width6 first">
                            <?=$this->layout()->content;?>
                        </div>
                        <div class="column width2" style="padding-top:10px">
                            <div class="corner-tl corner-tr corner-bl corner-br" style="border:1px solid #cecece;">
                                <div class="ta-left" style="padding:10px;">
                                <abbr><b>SELAMAT DATANG</b></abbr><br/><br/>
                                <abbr>Pengguna</abbr>:&nbsp;<?=Zend_Auth::getInstance()->getIdentity()->username; ?><br/>
                                <abbr>Group</abbr>:&nbsp;<?=$this->getGroupName(Zend_Auth::getInstance()->getIdentity()->packageId);?><br/><br/>
                                &raquo;&nbsp;<abbr><b>Kunjungan Terakhir Anda</b></abbr>:&nbsp;<br/>
                                <?=$this->lastLogin();?><br><br>
                                <?
								$sReturn = "http://".$_SERVER['SERVER_NAME'].$_SERVER['REQUEST_URI'];
								$sReturn = base64_encode($sReturn);
                                ?>
                                <a href="http://id.hukumonline.com/identity/logout/<?=$sReturn;?>">&raquo;&nbsp;Log Out</a>
                                </div>
                            </div>
                            <div style="padding-top:5px;"></div>
                            <div class="corner-tl corner-tr corner-bl corner-br" style="border:1px solid #cecece;">
                                <div class="ta-left" style="padding: 5px;">

                                    <ul id="psetting">
                                        <li>
                                            <h6><abbr>Dasbor Ku</abbr></h6>
                                            <a href="http://id.hukumonline.com/identity/profile">Dasbor</a><br>
                                            <a href="http://id.hukumonline.com/identity/upgrade">Ganti Paket</a>
                                        </li>
                                        <li>
                                            <h6><abbr>Kelola Profil</abbr></h6>
                                            <a href="http://id.hukumonline.com/identity/editprofile">Ubah Profil</a><br>
                                            <a href="http://id.hukumonline.com/identity/picture">Foto</a><br>
                                            <a href="http://id.hukumonline.com/identity/change.password">Ubah Sandi</a><br>
                                            <a href="http://id.hukumonline.com/identity/changeemail">Ubah Email</a><br>
                                        </li>
                                        <li>
                                            <h6><abbr>Laporan</abbr></h6>
                                            <a href="http://store.hukumonline.com/store/payment/list">Sejarah Pesanan</a><br>
                                            <a href="http://store.hukumonline.com/store/payment/transaction">Sejarah Transaksi</a><br>
                                            <a href="http://store.hukumonline.com/store/payment/confirm">Konfirmasi Pembayaran</a><br>
                                            <a href="http://store.hukumonline.com/store/payment/billing">Ubah Informasi Tagihan</a>
                                        </li>
                                        <li>
                                            <h6><abbr>Dokumen Ku</abbr></h6>
                                            <a href="http://store.hukumonline.com/store/payment/document">Lihat Semua</a>
                                        </li>
                                        <li>
                                            <h6><abbr>Berlangganan</abbr></h6>
                                            <a href="#">Berita Berkala</a><br>
                                            <a href="#">Pemberitahuan Blackberry</a>
                                        </li>
                                    </ul>

                                </div>
                            </div>
                            <div style="padding-top:5px"></div>
                            <div class="corner-tl corner-tr corner-bl corner-br" style="border:1px solid #cecece;">
                                <div class="ta-left" style="padding:10px;">
                                    <abbr>Satu Hukumonline!ID</abbr>
                                    Gunakan ID anda untuk Hukumonline Indonesia, Hukumonline English, Hukumpedia dan Forum.
                                </div>
                            </div>
                        </div>
                    </div>

                </section>

            </div>
        </div>
    </body>
</html>