<div class="align-left">
&nbsp;
</div>
<div class="align-right">
	<a href="<?=ROOT_URL;?>/shop/testimonial/add">Add</a>
</div>
<div class="clear">&nbsp;</div>
<hr>
<div class="content-box corners">
<header>
    <h3><img src="<?=$this->cdn('images');?>/information.png" alt="" />Testimonials</h3>
</header>
<section>
    <p>Proin elit arcu, rutrum commodo, vehicula tempus, commodo a, risus. Curabitur nec arcu. Donec sollicitudin mi sit amet mauris. Nam elementum quam ullamcorper ante. Etiam aliquet massa et lorem. Mauris dapibus lacus auctor risus. Aenean tempor ullamcorper leo. Vivamus sed magna quis ligula eleifend adipiscing. Duis orci. Aliquam sodales tortor vitae ipsum. Aliquam nulla. Duis aliquam molestie erat. Ut et mauris vel pede varius sollicitudin. Sed ut dolor nec orci tincidunt interdum. Phasellus ipsum. Nunc tristique tempus lectus.</p>
    <table class="no-style full">
    <tbody>
        <tr>
            <td><b>Users</b></td>
            <td class="ta-right">11</td>
        </tr>
        <tr>
            <td><b>Posts</b></td>
            <td class="ta-right">22</td>
        </tr>
        <tr>
            <td><b>Comments</b></td>
            <td class="ta-right">332</td>
        </tr>
    </tbody>
    </table>
</section>
</div>
