<div id="page">
<div class="wrapper">
	<section class="column first">
	<div class="column width8 first">
	
		<div class="footerMenu ta-center">
			<ul>
				<li><a href="">Syarat dan Ketentuan Belanja</a></li>
				<li><a href="">Kebijakan Privasi</a></li>
			</ul><br>
			<ul>
				<li><a href="">Syarat dan Ketentuan Redaksi</a></li>
				<li><a href="">Tentang Kami</a></li>
				<li><a href="">Produk dan Jasa</a></li>
				<li><a href="">Mitra Kami</a></li>
				<li><a href="">Kode Etik</a></li>
			</ul>
		</div>
		
		</div>
	</section>
</div>
</div>