<header id="holup">
	<div class="wrapper">
		<section class="column width8 first">
			<div class="colgroup leading">
				<div class="column width4 first">
					<div class="headerMenu">
						<ul>
							<li><a href="http://www.hukumonline.com">hukumonline.com</a></li>
							<li>|</li>
							<li><a href="http://en.hukumonline.com">en.hukumonline.com</a></li>
							<li>|</li>
							<li><a href="http://www.hukumpedia.com">hukumpedia.com</a></li>
						</ul>
					</div>
				</div>
				<div class="column width4">
					<div class="ta-right" style="padding-top:10px;">
					<form id="searchForm" method="POST" action="http://en2.hukumonline.com/app/dms/browser/search" style="display:inline;"> 
						<input type="text" id="searchQuery" name="searchQuery" size="100" style="width:250px"> 
						<input type="hidden" name="profile" value="">
						<input type="submit" value="Go" class="btn">
					</form>
					</div>
					<div class="ta-right">
					<a href="" style="color:white">Pencarian Lanjutan</a>
					</div>
				</div>
			</div>
		</section>
	</div>
</header>