<? $row = $this->row?>
<div class="span-33 append-2 prepend-2 prepend-top">
	<h2 class="alt">Selamat, pesanan anda telah direkam ke database kami.</h2>
	<hr>
<strong>
<br />
Pesanan anda telah dicatat dengan nomer pesanan : <font color="blue"><?=$row->orderId;?></font>.<br />
Untuk melanjutkan proses,  silahkan ikuti langkah-langkah berikut :
<ol>
	<li>Silahkan Cetak halaman ini. </li>
	<li>Silahkan pergi ke Bank dan transfer dana sebagaimana terdaftar dibawah ini. </li>
	<li>Konfirmasi transfer anda dengan salah satu metode ini :
		<ul>
			<li>Email di layanan@hukumonline.com </li>
			<li>Oleh web klik aja <a href="<?=KUTU_ROOT_URL?>/site/store_payment/confirm ">disini</a></li>
			<li>Hubungi layanan kami di (+62 21) 837 01827. </li>
			<li>atau fax ke (+62 21) 837 01826. </li>
		</ul>
	</li>
	<li>Harap bersabar dan menunggu pesanan anda.</li>
	<li>Pesanan anda akan siap sekitar 1-3 hari setelah konfirmasi.</li>
</ol>
<br />
</strong>
	<input type="button" value="Cetak" onclick="javascript:window.print();" class="btn">
	<br>&nbsp;
	<fieldset>
	<legend>Yang akan dicetak</legend>
	Order Id   : <?=$row->orderId; ?><br />
	Invoice    : <?=$row->invoiceNumber; ?> <br />
	Tax Number : <?=$row->taxNumber; ?> <br />
	Company : <?=$row->taxCompany; ?><br />
	Address : <?=$row->taxAddress; ?><br />
	City : <?=$row->taxCity; ?> <br />
	ZIP Code : <?=$row->taxZip; ?> <br />
	Province : <?=$row->taxProvince; ?>(<?=$row->taxCountryId; ?>)<br />
	Telp : <?=$row->telephone; ?> <br />
	Date : <?=$row->datePurchased; ?> <br />
	Total Fund Must be transfered : <strong><?=$row->orderTotal; ?></strong> <br />
	</fieldset>
 	<hr class ='white'>
</div>

