<?php
/**
 * @package kutump
 * @copyright 2008-2009 hukumonline.com/en.hukumonline.com
 * @author Nihki Prihadi <nihki@hukumonline.com>
 *
 * $Id: redirectUrl.phtml 2009-01-21 16:08: $
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>hukumonline.com Membership</title>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<link rel="shortcut icon" href="<?=$this->baseUrl;?>/resources/images/hole_small.ico" />
	<script type="text/javascript" src="<?=$this->baseUrl; ?>/js/jquery/jquery-1.2.3.pack.js"></script>
	<link rel="stylesheet" type="text/css" media="all" href="<?=$this->baseUrl;?>/resources/css/elastic.css" />
	<script src="<?=$this->baseUrl;?>/resources/css/elastic.js" type="text/javascript" language="javascript" charset="utf-8"></script>
	<link rel="stylesheet" type="text/css" media="screen" href="<?=$this->baseUrl;?>/resources/css/typography.css" />
	<style type="text/css">
	.tborder { background: #ffffff;	color: #000000;	border: 1px solid #dadada; }
	.tcat {	background: #ddd url(/assets/images/item-hd.gif) repeat-x 0 bottom;	color: #222; font-size: 12px; font-weight:bold;	padding:3px; }
	.panel { background: #f1f1f1; color: #000000; padding: 10px; border:0 none; }
	.panelsurround { background: #f1f1f1; color: #000000; }
	</style>
	<script type="text/javascript">
	function delayedRedirect(){
	//    window.location = "<?php //echo $this->login ?>"
	    window.location = "<?=$this->getKutuRootUrl(); ?>"
	}
	</script>
</head>
<body onLoad="setTimeout('delayedRedirect()', 3000)">
	<div class="unit horizontal-center layout">
		<div class="container" style="padding-top:15px;">
			<img src="<?=$this->cdn('images'); ?>/holid.jpg" alt="mnutopshadow" />
			<div style="font-size:10px;padding-top:2px;border-bottom:1px solid #ddd;">Buat Akun HukumonlineID</div>
			<div style="float:right;font-size:12px;">
				<a href="<?=$this->getKutuRootUrl();?>">Awal</a> | <a href="<?=$this->baseUrl;?>/identity/daftar">Daftar</a>
			</div>
			<div style="clear:both;"></div>
			<div style="padding-top:10px;"></div>
			<table class="tborder" cellpadding="6" cellspacing="1" border="0" width="70%" align="center">
			<tr>
				<td class="tcat">Redirecting...</td>
			</tr>
			<tr>
				<td class="panelsurround" align="center">
				<div class="panel">
						
					<blockquote>
			
						<p>&nbsp;</p>
						<p><strong>Welcome to Hukumonline, <?=$this->username ?>.</strong></p>			
						
							<p class="smallfont"><a href="<?=$this->getKutuRootUrl(); ?>">Click here if your browser does not automatically redirect you.</a></p>
							<div>&nbsp;</div>
						
					</blockquote>
						
				</div>
				</td>
			</tr>
			</table>			
		</div>
	</div>
	<div id="ft">	
	<div class="unit">
		<div class="container footer">
		<a href="<?=$this->baseUrl;?>/identity/feedback">Feedback</a> | <a href="http://hukumonline.blogspot.com/">Blog</a> | Copyright &copy; 2008 Hukumonline		
		</div>
	</div>
	</div>


</body>
</html>